### ISSUE TITLE
[CÓDIGO] Falha na devolução do saldo #10

### ISSUE THREAD

**Issue by enggiovanelli** [GuimaraesR/Source-Code-Inspection#10]
Tipo de defeito: Funcionalidade
Comentários: Saldo não é zerado mesmo quando o troco é devolvido.
Severidade: Alta
Correção na função getTroco()

**Comment by enggiovanelli** [comment]
Correção na função getTroco()

public Iterator getTroco() {
Iterator troco = new Troco(this.saldo).getIterator();
saldo = 0;
return troco;
}

**Comment by GuimaraesR** [comment]
public Troco(int valor) {
        papeisMoeda = new PapelMoeda[6];
        int count = 0;
        
        while (valor >= 100) {
            valor = valor - 100;
            count++;
        }
        papeisMoeda[5] = new PapelMoeda(100, count);
        count = 0;
        
        while (valor >= 50) {
            valor = valor - 50;
            count++;
        }
        papeisMoeda[4] = new PapelMoeda(50, count);
        count = 0;
        
        while (valor >= 20) {
            valor = valor - 20;
            count++;
        }
        papeisMoeda[3] = new PapelMoeda(20, count);
        count = 0;
        
        while (valor >= 10 ) {
            valor =  valor - 10;
            count++;
        }
        papeisMoeda[2] = new PapelMoeda(10, count);
        count = 0;
        
        while (valor >= 5) {
            valor = valor-  5;
            count++;
        }
        papeisMoeda[1] = new PapelMoeda(5, count);
        count = 0;
        
        while (valor >= 2) {
             valor = valor -  2;
            count++;
        }
        papeisMoeda[0] = new PapelMoeda(2, count);
    }

    public Iterator<PapelMoeda> getIterator() {
        return new TrocoIterator(this.papeisMoeda);
    }

    class TrocoIterator implements Iterator<PapelMoeda> {

        protected PapelMoeda[] troco;
    	int posicao = 0;

        public TrocoIterator(PapelMoeda[] troco) {
            this.troco = troco;
        }
