### ISSUE TITLE
[CÓDIGO] Laços mal implementado na Classe Troco.java #12

### ISSUE THREAD

**Issue by enggiovanelli** [GuimaraesR/Source-Code-Inspection#12]
•	Severidade:  Alta
•	Tipo de problema:  Dados
•	Descrição:  Laço mal implementado, nas linhas 67  -  71.

for (int i = 6; i >= 0; i++) {
    if (troco.papeisMoeda[i] != null) {
        return true;
    }
}

**Comment by GuimaraesR** [comment]
public TrocoIterator(PapelMoeda[] troco) { // Correção
            this.troco = troco;
        }
