### ISSUE TITLE
[CÓDIGO] Funçao getTroco() #4

### ISSUE THREAD

**Issue by enggiovanelli** [GuimaraesR/Source-Code-Inspection#4]
• Severidade: Média
• Tipo de problema: Comissão
• Descrição: A função getTroco() na linha 39 não executa como previsto pelo Diagrama de sequencia na Documentação
    public Iterator<Integer> getTroco() {
        return null;
    }

**Comment by GuimaraesR** [comment]
public Iterator<PapelMoeda> getTroco() {
    	Iterator<PapelMoeda> notaIterator = new Troco(saldo).getIterator();
    	
    	while (notaIterator.hasNext()) {
    		PapelMoeda nota = (PapelMoeda)notaIterator.next();
    		System.out.println("valor: "+ nota.getValor() +" | quantidade: " + nota.getQuantidade());
    	}
        return notaIterator;
