### ISSUE TITLE
[CÓDIGO] Função imprimir() #6

### ISSUE THREAD

**Issue by enggiovanelli** [GuimaraesR/Source-Code-Inspection#6]
• Severidade: Médio.
• Tipo de problema: Comissão.
• Descrição: O funcionamento da função imprimir na linha 48 da Classe _"TicketMachine"_ difere de como foi descrito no diagrama de sequencia 2.4 Diagrama de Sequencia -- Solicitar bilhete da documentação

public String imprimir() throws SaldoInsuficienteException {
        if (saldo < valor) {
            throw new SaldoInsuficienteException();
        }
        String result = "*****************\n";
        result += "*** R$ " + saldo + ",00 ****\n";
        result += "*****************\n";
        return result;
    }

**Comment by GuimaraesR** [comment]
public String imprimir() throws SaldoInsuficienteException {
        if (saldo < valor) {
          throw new SaldoInsuficienteException("O seu saldo é insuficiente");
        }
        
        subtraiBilheteDoSaldo();
        getTroco();
        String result = "*****************\n";
        result += "*** R$ " + valor + ",00 ****\n";
        result += "*****************\n";
        
        
        return result;
    }
