### ISSUE TITLE
[CÓDIGO] Função inserir() #9

### ISSUE THREAD

**Issue by GuimaraesR** [GuimaraesR/Source-Code-Inspection#9]
· Severidade: Alta
· Tipo de problema: Comissão, Excesso
· Descrição: O método foi implementado de forma errônea, descaracterizando o funcionamento da função devido ao excesso do loop.

**Comment by enggiovanelli** [comment]
public void inserir(int quantia) throws PapelMoedaInvalidaException {
        boolean achou = false;
        for (int i = 0; i < papelMoeda.length && !achou; i++) {
            if (papelMoeda[i] == quantia) {
                achou = true;
            }
        }
        if (!achou) {
            throw new PapelMoedaInvalidaException("o papel moeda é invalido");
        }
        this.saldo += quantia;
    }

    public int getSaldo() {
        return saldo;
    }
